#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.LongSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  instance:
    prefer-ip-address: true